portal_cadastro_relatorio:
    resource: "@PortalBundle/Controller/CadastroRelatorioController.php"
    type:     annotation

portal_relatorio_dinamico:
    resource: "@PortalBundle/Controller/RelatorioDinamicoController.php"
    type:     annotation

portal_grupo_usuarios:
    resource: "@PortalBundle/Controller/GrupoUsuariosController.php"
    type:     annotation

portal_permissoes:
    resource: "@PortalBundle/Controller/PermissoesController.php"
    type:     annotation

portal_usuario:
    resource: "@PortalBundle/Controller/UsuarioController.php"
    type:     annotation

portal_usuario_permissao:
    resource: "@PortalBundle/Controller/UsuarioPermissaoController.php"
    type:     annotation

portal:
    resource: "@PortalBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
